#!/usr/bin/env node

'use strict';

const Path = require('path');

const ruleBaseDir = Path.join(__dirname, '../node_modules/eslint/lib/rules/');

const rule = process.argv[2];
const {docs} = require(Path.join(ruleBaseDir, `${rule}.js`)).meta;

// eslint-disable-next-line no-console
console.log(JSON.stringify(docs, null, 4));
