#!/usr/bin/env node

'use strict';

const util = require('lodash');
const Path = require('path');

const ruleBaseDir = Path.join(__dirname, '../node_modules/eslint/lib/rules/');

const rule = process.argv[2];
const {docs} = require(Path.join(ruleBaseDir, `${rule}.js`)).meta;

console.log(JSON.stringify(docs, null, 4));
